// Copyright (c) 2004 Adam Karpierz
// SPDX-License-Identifier: CC-BY-NC-ND-4.0 OR LicenseRef-Proprietary
// Please refer to the accompanying LICENSE file.

package org.python;

import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.io.InputStream;
import java.util.Arrays;
import java.util.Collection;
import java.util.EnumSet;
import java.util.Properties;
import java.util.Set;

/**
 * Python version information.
 *
 * The version number and build information are loaded from the
 * version.properties file, located in this class file's directory.
 * version.properties is generated by jvm.java.org.python.Version.update().
 */
public class Version
{
    /** The current version of Python. */
    public static String PY_VERSION;

    /** Tokenized version. */
    public static int PY_MAJOR_VERSION;
    public static int PY_MINOR_VERSION;
    public static int PY_MICRO_VERSION;
    public static int PY_RELEASE_LEVEL;
    public static int PY_RELEASE_SERIAL;

    /** Timestamp of the current build. */
    public static String DATE;
    public static String TIME;

    /**
     * Current Git branch {@code git name-rev --name-only HEAD},
     * Current Git tag {@code git describe --all --always --dirty}, e.g. 'tip',
     * Current Git global revision id {@code git rev-parse --short HEAD}.
     */
    private static String GIT_BRANCH;
    private static String GIT_TAG;
    private static String GIT_VERSION;

    /** The current Python executable. */
    public static String PY_EXECUTABLE;
    /** The current Python shared library. */
    public static String PY_SHAREDLIB;

    static
    {
        loadProperties();
    }

    /**
     * Return the current git version number.
     * May be an empty string on environments that can't determine it.
     */
    public static String getGitVersion()
    {
        return GIT_VERSION;
    }

    /**
     * Return the current git identifier name, normally the current tag, falling
     * back to the branch.
     */
    public static String getGitIdentifier()
    {
        return "".equals(GIT_TAG) || "undefined".equals(GIT_TAG) ? GIT_BRANCH : GIT_TAG;
    }

    /**
     * Return the current build information, including revision and timestamp.
     */
    public static String getBuildInfo()
    {
        String revision  = getGitVersion();
        String separator = "".equals(revision) ? "" : ":";
        String gitId     = getGitIdentifier();
        return String.format("%s%s%s, %.20s, %.9s",
                             gitId, separator, revision, DATE, TIME);
    }

    /**
     * Return the Python version, including compiler (or in our case, the Java VM).
     */
    public static String getVersion()
    {
        return String.format("%.80s (%.80s)\n%.80s",
                             PY_VERSION, getBuildInfo(), getVM());
    }

    /**
     * Describe the current Java VM.
     */
    public static String getVM()
    {
        return String.format("[%s (%s)]",
                             System.getProperty("java.vm.name"),
                             System.getProperty("java.vm.vendor"));
    }

    /**
     * Load the version information from the properties file.
     */
    private static void loadProperties()
    {
        boolean loaded = false;
        final String versionProperties = "/org/python/version.properties";
        InputStream in = Version.class.getResourceAsStream(versionProperties);
        if ( in != null )
        {
            try
            {
                Properties properties = new Properties();
                properties.load(in);
                loaded = true;

                PY_VERSION        = properties.getProperty("jvm.python.version");
                PY_MAJOR_VERSION  = Integer.parseInt(properties.getProperty("jvm.python.major_version"));
                PY_MINOR_VERSION  = Integer.parseInt(properties.getProperty("jvm.python.minor_version"));
                PY_MICRO_VERSION  = Integer.parseInt(properties.getProperty("jvm.python.micro_version"));
                PY_RELEASE_LEVEL  = Integer.parseInt(properties.getProperty("jvm.python.release_level"));
                PY_RELEASE_SERIAL = Integer.parseInt(properties.getProperty("jvm.python.release_serial"));

                DATE = properties.getProperty("jvm.python.build.date");
                TIME = properties.getProperty("jvm.python.build.time");

                GIT_BRANCH  = properties.getProperty("jvm.python.build.git_branch");
                GIT_TAG     = properties.getProperty("jvm.python.build.git_tag");
                GIT_VERSION = properties.getProperty("jvm.python.build.git_version");

                PY_EXECUTABLE = properties.getProperty("jvm.python.executable");
                PY_SHAREDLIB  = properties.getProperty("jvm.python.sharedlib");
            }
            catch ( IOException exc )
            {
                System.err.println("There was a problem loading " + versionProperties + ":");
                exc.printStackTrace();
            }
            finally
            {
                try
                {
                    in.close();
                }
                catch ( IOException exc )
                {
                    /* ok */
                }
            }
        }
        if ( ! loaded )
        {
            /* fail with a meaningful exception (cannot use Py exceptions here) */
            throw new RuntimeException("unable to load " + versionProperties);
        }
    }
}
